### ISSUE TITLE
Substitution for id

### ISSUE THREAD

**Issue by PeterJanic** [CodePilotNavin/BruteBot#2]
Hello, I see that program uses ID of username, pass and button...but what if on website is none id for those...only class or something different?

**Comment by navin-maverick** [comment]
Hey @PeterJanic, thanks for trying BruteBot.

To answer your question, the program would require slight modifications. Specifically, lines 206-210 and lines 316-328 where those parameters are consumed by the program. You can try tweaking the parameter types to accommodate your new values. Let me know if it works.

**Comment by CodePilotNavin** [comment]
Here's how you can modify the `validate_elements` function to use class names instead of IDs:

```python
def validate_elements(val_brutebot):
    global val2_output

    tmp_driver = Browser(showWindow=False, proxy=brutebot.proxy)
    tmp_driver.go_to(val_brutebot.target)
    time.sleep(val_brutebot.time_in_seconds)

    x = tmp_driver.exists(val_brutebot.uid, css_selector=str('input[type=text][class="{}"]').format(brutebot.uid))
    y = tmp_driver.exists(val_brutebot.pid, css_selector=str('input[type=password][class="{}"]').format(brutebot.pid))
    z = tmp_driver.exists(val_brutebot.button_name, css_selector=str('button[class="{}"]').format(brutebot.button_name))

    if x and y and z:
        time.sleep(val_brutebot.time_in_seconds)
        tmp_driver.close_current_tab()
        val2_output = True
        print_green(f"[!] The specified URL and the login page elements seem OK.\n")
        sys.exit()
    else:
        print_red(
            '[!] Error: The specified URL / login page elements could not be found. Please check & try again.\n\n'
            '[!] Exiting program!\n')
        val2_output = False
        sys.exit()
```

This modification will make the script search for the username, password, and login button elements based on their class names rather than their IDs.
