### ISSUE TITLE
NEED HELP PLEASE!

### ISSUE THREAD

**Issue by Zmotala36** [CodePilotNavin/BruteBot#3]
Hi i was working with this tool but when I tried to run it this is what came up 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/BruteBot/BruteBot.py", line 202, in validate_elements
    tmp_driver = Browser(showWindow=False, proxy=brutebot.proxy)
  File "/usr/local/lib/python3.9/dist-packages/webbot/webbot.py", line 72, in __init__
    [setattr(self, function, getattr(self.driver, function)) for function in
  File "/usr/local/lib/python3.9/dist-packages/webbot/webbot.py", line 72, in <listcomp>
    [setattr(self, function, getattr(self.driver, function)) for function in
AttributeError: 'WebDriver' object has no attribute 'switch_to_alert

this is the command 

└─$ sudo python3 BruteBot.py -t https://accounts.snapchat.com/accounts/login -u Zmotala36 -p Zmotala36.txt --uid username --pid password --bname Login

**Comment by CodePilotNavin** [comment]
The error message indicates that the `WebDriver` object does not have the `switch_to_alert` attribute, which suggests that the `webbot` library is attempting to use a method that is not available in the underlying Selenium WebDriver.

To resolve this issue, you can modify the `webbot` library's code to use the correct method for handling alerts. The `switch_to_alert` method was deprecated in newer versions of Selenium in favor of `switch_to.alert`.

Here's how you can modify the `webbot` library's `webbot.py` file to fix this issue:

1. Open the `webbot.py` file located in `/usr/local/lib/python3.9/dist-packages/webbot/` (or a similar directory depending on your Python installation).
2. Find the line that contains `switch_to_alert` and replace it with `switch_to.alert`.

Before modification (incorrect):
```python
[setattr(self, function, getattr(self.driver, function)) for function in dir(WebDriver) if
         not function.startswith('_')]
```

After modification (correct):
```python
[setattr(self, function, getattr(self.driver, function)) for function in dir(WebDriver) if
         not function.startswith('_') and 'switch_to_alert' not in function]
```

This change should resolve the `AttributeError` related to `switch_to_alert` and allow the `webbot` library to function correctly.

**Comment by Gotokolu** [comment]
> In my Windows terminal There is an error called 'TypeError: webdriver.**init**() got an unexpected keyword argument 'executable_path'
