### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by golfymate** [CodePilotNavin/BruteBot#4]
Hello, is this project maintained?

I am getting some erros and from what I understand, is it selenium chromedriver issue or something else?

Thanks in advance

> Exception in thread Thread-2 (validate_elements):
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Administrator\Desktop\hydra\BruteBot.py", line 202, in validate_elements
>     tmp_driver = Browser(showWindow=False, proxy=brutebot.proxy)
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webbot\webbot.py", line 68, in __init__
>     self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
>     super().__init__(
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__
>     super().__init__(
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
>   (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.19045 x86_64)
>

**Comment by bob69420x** [comment]
python3 BruteBot.py -t 127.0.0.1 -u admin -p wordlist --uid username --pid password --bname Login -m headless
